### ISSUE TITLE
Good stuff

### ISSUE THREAD

**Issue by mcw0** [tothi/pwn-hisilicon-dvr#2]
Thanks for sharing!

BTW, You know that XM and Dahua share a lot of same code?

Your 'sofia_hash.py' proves that, and I'm happy to see that one in Python2, going to steal that piece of code from you in one project of mine. (Will of course tell it's your code)

Best, bashis

**Comment by tothi** [comment]
nice. feel free to use the code. ;)
btw, didnt know. unfortunately dont have any Dahua device.
i wouldnt be surprised if those Dauha devices have some kind of overflow vulnerabilities like these.

**Comment by nsknyc** [comment]
2019 and this is still relevant. Didn't want to open another 'good work' issue. I have 4 decommisioned boxes at my place which were used at my store. While working with them I found a couple of the same vulnerabilities, a quick google led me to this repo. It's unfortunate that these boxes are still in use everywhere where i live. Whenever I go out to coffee shops or places with free wifi, I would poke around the networks and lo-an-behold there they are. I'm thinking about patching these issues on my boxes and putting them back to work. Anyways thanks for all the work!

**Comment by tothi** [comment]
thx, yw. IoT is seriously insecure. usually vulnerabilities remain unpatched due to lack of updating mechanisms. and (like in most of such cases) the vendor didnt bother about this vulnerabilty, of course reported them, but got no answer. so there was no other option than public disclosure. ;)

**Comment by Cool-Y** [comment]
Great job！
But I cannot get a root shell through connecting to 9527/tcp (by raw netcat)，can you give me more information？thank you^^
<pre>PORT      STATE    SERVICE       VERSION
80/tcp    open     http          uc-httpd 1.0.0
514/tcp   filtered shell
554/tcp   open     rtsp
9530/tcp  open     unknown
34567/tcp open     dhanalakshmi?
</pre>

<pre><font color="#55FF55"><b>han@ubuntu</b></font>:<font color="#5555FF"><b>~/ck</b></font>$ nc 192.168.31.188 9530
ls

</pre>

**Comment by tothi** [comment]
@Cool-Y: here it is, released just now: https://github.com/tothi/hs-dvr-telnet ;)
